// app/layout.js
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';
import '../styles/globals.css'; // Ensure global styles are imported here
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className="font-questrial text-dark bg-light">
        <div className="shadow-lg shadow-dark/30 sticky top-0 z-50 bg-primary">
          <Navbar />
        </div>
        <main className="flex-grow">{children}</main>
        <div>
          <Footer />
        </div>
        <Analytics />
      </body>
    </html>
  );
}
